### PR TITLE
TCP output stream

### PR DESCRIPTION
**Pull request by chantra**
This change enables writing messages read from input out to a TCP
server.
One of the reason to do that would be to offload dnstap processing outside the DNS host. Many servers currently write dnstap messages to a unix socket, this would allow sending those messages to another host and move the processing there, lifting off some pressure out of the DNS host.
The original goal of this hack was to allow demultiplexing the input stream to multiple remote TCP servers, but in order to achieve that, some changes would be needed to the current golang-dnstap logic in order to attach multiple output stream subscribing to the input messages generated by the input stream.

One caveat currently is that if the TCP connection would die, then the process would exit due to a log.Fatalf that would handle the error. This could be handled in subsequent diffs but some refactoring needs to happen first.

### Usage/Test plan
run a server to listen on `[::1]:1234` and print out messages:
```
go run dnstap/main.go -l '[::1]:1234'
```

then to send messages read from `/tmp/test.dnstap` to server
`[::1]:1234`:
```
go run dnstap/main.go -r /tmp/test.dnstap -W '[::1]:1234'
```

55453726_2292292237711849_4602339963432861696_o

### CODE REVIEW

**Comment by cmikk** [comment]
Thanks for this work.

I think the TCP code would be better kept out of _FrameStreamOutput_ which is oriented toward regular files, and put in a new _FrameStreamSockOutput_, a separation like we currently have on dnstap input. I've prototyped this approach on the [tcp-output](https://github.com/dnstap/golang-dnstap/commits/tcp-output) branch. If that looks good to you, we can work on integrating that into the dnstap utility.

As for sending data to multiple servers, I would suggest an approach like:
```go
func fanOut(addrs ...net.Addr) chan<- []byte {
    var outputs []*FrameStreamSockOutput
    for _, addr := range addrs {
        output, err := NewFrameStreamSockOutput(addr, nil)
        outputs = append(outputs, output)
        go output.RunOutputLoop()
    }
    ch := make(chan []byte, 100)
    go func() {
        for b := range ch {
            // Extended filtering or demultiplexing logic can go here.
            for _, o := range outputs {
                o.GetOutputChannel() <- b
            }
        }
    }()
    return ch
}

....

    input.ReadInto(fanOut(addrs...))
```

**Comment by chantra** [comment]
@cmikk what you did look good to me.

**Comment by chantra** [comment]
@cmikk do you want to take it from there?

**Comment by cmikk** [comment]
Certainly. Please take a look at the branch 'tcp-output'. It adds "-T <host:port>" and "-U <path>" options to send output to TCP and Unix domain sockets, respectively. It only supports a single output for now. I have multiple outputs in the works but it is a larger refactor.

The 'tcp-output' branch code requires code in the 'add-timeout' branch of github.com/farsightsec/golang-framestream

**Comment by cmikk** [comment]
This functionality was added in #23, and merged.

**Comment by chantra** [comment]
Thanks @cmikk !

**Pull request closed without merging**
